package com.wiitel.tvhelper.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APP_FLOW".
*/
public class AppFlowDao extends AbstractDao<AppFlow, Long> {

    public static final String TABLENAME = "APP_FLOW";

    /**
     * Properties of entity AppFlow.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Key = new Property(0, long.class, "key", true, "_id");
        public final static Property CurrentMonth = new Property(1, String.class, "currentMonth", false, "CURRENT_MONTH");
        public final static Property Appid = new Property(2, int.class, "appid", false, "APPID");
        public final static Property RxHistory = new Property(3, long.class, "rxHistory", false, "RX_HISTORY");
        public final static Property TxHistory = new Property(4, long.class, "txHistory", false, "TX_HISTORY");
    };


    public AppFlowDao(DaoConfig config) {
        super(config);
    }
    
    public AppFlowDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APP_FLOW\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: key
                "\"CURRENT_MONTH\" TEXT NOT NULL ," + // 1: currentMonth
                "\"APPID\" INTEGER NOT NULL ," + // 2: appid
                "\"RX_HISTORY\" INTEGER NOT NULL ," + // 3: rxHistory
                "\"TX_HISTORY\" INTEGER NOT NULL );"); // 4: txHistory
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_APP_FLOW_APPID_CURRENT_MONTH ON APP_FLOW" +
                " (\"APPID\" ASC,\"CURRENT_MONTH\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APP_FLOW\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AppFlow entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getKey());
        stmt.bindString(2, entity.getCurrentMonth());
        stmt.bindLong(3, entity.getAppid());
        stmt.bindLong(4, entity.getRxHistory());
        stmt.bindLong(5, entity.getTxHistory());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AppFlow entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getKey());
        stmt.bindString(2, entity.getCurrentMonth());
        stmt.bindLong(3, entity.getAppid());
        stmt.bindLong(4, entity.getRxHistory());
        stmt.bindLong(5, entity.getTxHistory());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public AppFlow readEntity(Cursor cursor, int offset) {
        AppFlow entity = new AppFlow( //
            cursor.getLong(offset + 0), // key
            cursor.getString(offset + 1), // currentMonth
            cursor.getInt(offset + 2), // appid
            cursor.getLong(offset + 3), // rxHistory
            cursor.getLong(offset + 4) // txHistory
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AppFlow entity, int offset) {
        entity.setKey(cursor.getLong(offset + 0));
        entity.setCurrentMonth(cursor.getString(offset + 1));
        entity.setAppid(cursor.getInt(offset + 2));
        entity.setRxHistory(cursor.getLong(offset + 3));
        entity.setTxHistory(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AppFlow entity, long rowId) {
        entity.setKey(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AppFlow entity) {
        if(entity != null) {
            return entity.getKey();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
