package com.wiitel.tvhelper.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wiitel.tvhelper.data.AppFlow;

import com.wiitel.tvhelper.data.AppFlowDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appFlowDaoConfig;

    private final AppFlowDao appFlowDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appFlowDaoConfig = daoConfigMap.get(AppFlowDao.class).clone();
        appFlowDaoConfig.initIdentityScope(type);

        appFlowDao = new AppFlowDao(appFlowDaoConfig, this);

        registerDao(AppFlow.class, appFlowDao);
    }
    
    public void clear() {
        appFlowDaoConfig.getIdentityScope().clear();
    }

    public AppFlowDao getAppFlowDao() {
        return appFlowDao;
    }

}
